# Generated by Django 5.1.6 on 2025-03-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_recipeingredient_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
