# Generated by Django 5.1.6 on 2025-03-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_recipe_created_on_recipe_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='task_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
