# Generated by Django 5.1.6 on 2025-03-24 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_remove_recipe_task_image_recipeimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeimage',
            old_name='task_image',
            new_name='recipe_image',
        ),
    ]
